name: Java Lint

permissions:
  contents: read

on: [push, pull_request]

jobs:
  lint:
    name: Code Formatting Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*', '**/gradle.properties', '**/*gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Execution permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Clean corrupted Gradle cache
        run: |
          rm -rf ~/.gradle/caches/jars-* || true
          rm -rf ~/.gradle/caches/modules-*/files-* || true
          rm -rf ~/.gradle/caches/*/generated-gradle-jars || true

      - name: Spotless Check
        run: ./gradlew spotlessCheck --continue --no-daemon --refresh-dependencies
        continue-on-error: true

      - name: PMD Main Check
        run: ./gradlew pmdMain --continue --no-daemon
        continue-on-error: true

      - name: PMD Test Check
        run: ./gradlew pmdTest --continue --no-daemon
        continue-on-error: true
